### ISSUE TITLE
Project status ? quick questions ?! 

### ISSUE THREAD

**Issue by roscopecoltran** [ndob/yarrar#1]
Hi Niki,

Hope you are all well !

Wanted to ask about the status of your project, was it a school project ? why did u stopped the developement of yarrar as it sounds really promising ?

Yarrar would be cool with the following additions:

Dependencies that would have made it easier to finish:
- Dynamic native code plugins for unity3d: https://github.com/shadowmint/unity-n-native
- Build c++ native plugins with more controls on CMake args: https://github.com/ruslo/hunter
  - Hunter packages: [OpenCV](https://github.com/ruslo/hunter/tree/master/examples/OpenCV), [OPENCV+QT5](https://github.com/headupinclouds/gatherer), [OGLES_GPU (GPGPU processing)](https://github.com/hunter-packages/ogles_gpgpu/tree/hunter.develop), [CCV](https://github.com/ruslo/hunter/tree/master/examples/ccv), [Caffe](https://github.com/ruslo/hunter/tree/master/examples/caffe), >+100 pkgs
- Cross-platform compilation with CMake: https://github.com/ruslo/polly

**## Distributed Detections on mobile devices:**
- **Distributed pipelines**, with [nanomsg](https://github.com/nanomsg/nanomsg) or [libmill](https://github.com/sustrik/libmill), for video multi-processing (eg: parallel slam+markerless+facial landmarks with performance optimizations like sharing the same input matrix from the webcam to requestseveral recognition services IPC or TCP for mobile devices): https://github.com/daniel-j-h/DistributedSearch, https://daniel-j-h.github.io/post/distributed-search-nanomsg-bond/

**## Pipeline features:**
- **Face Reconstruction** with [eos](https://github.com/patrikhuber/eos)+[dlib](blog.dlib.net/2016/10/hipsterize-your-dog-with-deep-learning.html): https://github.com/KeeganRen/FaceReconstruction
- **DeepLeaarning for iOS** (eg with Yolo) https://github.com/qq456cvb/DeepLearningKitForiOS
- **LSD-SLAM for iOS**: https://github.com/xorthat/MobileSLAM
- **ORB_SLAM2-IOS**: https://github.com/ygx2011/ORB_SLAM2-IOS
- **Marker based AR**: https://github.com/ygx2011/Marker_AR
- **TLD Tracking**: https://github.com/ygx2011/IOS_TLD_Tracking
- **Tracking deformable planars**: https://github.com/qq456cvb/RealTimeTrack
- **real time visual odometry:** https://github.com/halismai/bpvo
- **Image pre-processing pipeline:** https://github.com/halide/Halide

I stop here as there are many others ^^ , and lots of people are making cool separate AR projects but no cross-platform pipeline available as open source project.

Let me know what was the background of yarrar and did you drop anything related toward AR or Unity3D... ?!

Have a good week !

Cheers,
Richard

**Comment by ndob** [comment]
Hi Richard,
Thanks for the message!

I checked those links you provided and there are definately a lot of interesting stuff, that could improve this project.

The initial reasoning to build this library was twofolded: indeed there was no viable open source project doing this and secondly I wanted to develop my own understanding of AR further.

As for the current status of this project, I unfortunately have to admit, that it's in a frozen state. I landed a job to develop Vuforia AR SDK at PTC Inc., which is the main reason I am not able to continue developing this library further. However if you (or anybody else) wants to continue from here, I'd be glad to provide help and further thoughts about my initial plans for the library.

I'll leave this open if someone else wonders the same thing. :)

Best regards,
Niki
